#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 2020, Jan Cervenka

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

DEFAULT_SERVICE_HOST = '0.0.0.0'
DEFAULT_SERIVCE_PORT = 5000

QUEUE_NAME = 'service_queue'
REQUEST_TIMEOUT_SEC = 15
REQUEST_WAITING_SEC = 0.3
BACKEND_WAITING_SEC = 0.3
REQUEST_BATCH_SIZE = 32
